### ISSUE TITLE
Error: Unable to parse color

### ISSUE THREAD

**Issue by SkepticMystic** [david-tejada/rango#291]
I'm not immediately sure what causes the issue, but I get this on certain pages. Rango appears to continue works as normal.

```
Uncaught (in promise) Error: Unable to parse color from string: rgb(9, NaN, NaN)
    at new vr (content.65d0fa3e.js:15008:29)
    at dh.computeColors (content.65d0fa3e.js:20600:20)
    at dh.applyDefaultStyle (content.65d0fa3e.js:20710:12)
    at new dh (content.65d0fa3e.js:20567:37)
    at Ph.intersect (content.65d0fa3e.js:20945:92)
    at hh.Sh [as callback] (content.65d0fa3e.js:20865:37)
```

**Comment by david-tejada** [comment]
Can you share a page where this happens?

**Comment by SkepticMystic** [comment]
Sorry, I should have done that in the first place!
I don't remember atm, but I'll keep an eye out for the error again, and share the url

**Comment by david-tejada** [comment]
I think it has to do with the `rgbaToRgb` function here: https://github.com/david-tejada/rango/blob/main/src/content/utils/getEffectiveBackgroundColor.ts#L1C1-L17C2

The call to `Number.parseFloat` must be returning NaN under some circumstances. Let me know if you come across it again.
